version: '3.4'

services:

  savehere.webapi:
    image: ${DOCKER_REGISTRY-}saveherewebapi
    build:
      context: .
      dockerfile: SaveHere.WebAPI/Dockerfile
    environment:
      - "urls=http://0.0.0.0:8580"
      - PUID=1000
      - PGID=1000
    user: 0:0
    privileged: true
    volumes:
      - ./downloads:/app/downloads
      - ./db:/app/db:rw

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./downloads:/home/files/downloads
      - ./frontend:/home/files/frontend
    ports:
      - "172.17.0.1:18480:80"
      - "172.17.0.1:18443:443"
    environment:
      - PUID=1000
      - PGID=1000
    user: 0:0
    privileged: true

  filebrowser:
    image: filebrowser/filebrowser:s6
    volumes:
      - ./downloads:/srv
      - ./filebrowser/filebrowser.db:/database/filebrowser.db
      - ./filebrowser/settings.json:/config/settings.json
    environment:
      - PUID=1000
      - PGID=1000
    user: 0:0
    privileged: true
    restart: always