version: '3.4'

services:

  savehere.webapi:
    image: ${DOCKER_REGISTRY-}saveherewebapi
    build:
      context: .
      dockerfile: SaveHere.WebAPI/Dockerfile
    ports:
      - "8880:8580"
    environment:
      - "urls=http://0.0.0.0:8580"
    volumes:
      - ./downloads:/app/downloads
      - ./db:/app/db

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./downloads:/home/files/downloads
      - ./frontend:/home/files/frontend
    ports:
      - "80:80"
      - "443:443"

  filebrowser:
    image: filebrowser/filebrowser:s6
    volumes:
      - ./downloads:/srv
      - ./filebrowser/filebrowser.db:/database/filebrowser.db
      - ./filebrowser/settings.json:/config/settings.json
    environment:
      - PUID=1000
      - PGID=1000
    restart: always